//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PervasiveDigital.Scratch.DeploymentHelper.Extensibility.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IDriverViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, PervasiveDigital.Scratch.DeploymentHelper.Extensibility.Contracts.IDriverContract
    {
        private PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IDriver _view;
        public IDriverViewToContractAddInAdapter(PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IDriver view)
        {
            _view = view;
        }
        public virtual void Start(PervasiveDigital.Scratch.DeploymentHelper.Extensibility.Contracts.IFirmataEngineContract firmataEngine)
        {
            _view.Start(PervasiveDigital.Scratch.DeploymentHelper.Extensibility.AddInSideAdapters.IFirmataEngineAddInAdapter.ContractToViewAdapter(firmataEngine));
        }
        public virtual void Stop()
        {
            _view.Stop();
        }
        public virtual void StartOfProgram()
        {
            _view.StartOfProgram();
        }
        public virtual void ExecuteCommand(string verb, string id, System.AddIn.Contract.IListContract<string> args)
        {
            _view.ExecuteCommand(verb, id, System.AddIn.Pipeline.CollectionAdapters.ToIList<string>(args));
        }
        public virtual System.Collections.Generic.Dictionary<string, string> GetSensorValues()
        {
            return _view.GetSensorValues();
        }
        internal PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IDriver GetSourceView()
        {
            return _view;
        }
    }
}

