//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PervasiveDigital.Scratch.DeploymentHelper.Extensibility.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IFirmwareConfigurationViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, PervasiveDigital.Scratch.DeploymentHelper.Extensibility.Contracts.IFirmwareConfigurationContract
    {
        private PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IFirmwareConfiguration _view;
        public IFirmwareConfigurationViewToContractAddInAdapter(PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IFirmwareConfiguration view)
        {
            _view = view;
        }
        public virtual void Configure()
        {
            _view.Configure();
        }
        internal PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IFirmwareConfiguration GetSourceView()
        {
            return _view;
        }
    }
}

