//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PervasiveDigital.Scratch.DeploymentHelper.Extensibility.AddInSideAdapters
{
    
    public class IFirmataEngineAddInAdapter
    {
        internal static PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IFirmataEngine ContractToViewAdapter(PervasiveDigital.Scratch.DeploymentHelper.Extensibility.Contracts.IFirmataEngineContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IFirmataEngineViewToContractAddInAdapter))))
            {
                return ((IFirmataEngineViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IFirmataEngineContractToViewAddInAdapter(contract);
            }
        }
        internal static PervasiveDigital.Scratch.DeploymentHelper.Extensibility.Contracts.IFirmataEngineContract ViewToContractAdapter(PervasiveDigital.Scratch.DeploymentHelper.Extensibility.IFirmataEngine view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IFirmataEngineContractToViewAddInAdapter)))
            {
                return ((IFirmataEngineContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IFirmataEngineViewToContractAddInAdapter(view);
            }
        }
    }
}

