//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PervasiveDigital.Scratch.DeploymentHelper.Extensibility
{
    
    [System.AddIn.Pipeline.AddInBaseAttribute()]
    public interface IDriver
    {
        void Start(IFirmataEngine firmataEngine);
        void Stop();
        void StartOfProgram();
        void ExecuteCommand(string verb, string id, System.Collections.Generic.IList<string> args);
        System.Collections.Generic.Dictionary<string, string> GetSensorValues();
        void ProcessDigitalMessage(int port, int value);
        void ProcessAnalogMessage(int port, int value);
        void ProcessExtendedMessage(byte command, byte[] data);
    }
}

