//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PervasiveDigital.Scratch.DeploymentHelper.Extensibility
{
    
    [System.AddIn.Pipeline.AddInBaseAttribute()]
    public interface IFirmataEngine
    {
        void ReportDigital(byte port, int value);
        void SendDigitalMessage(byte port, int value);
        void SendExtendedMessage(byte command, byte[] data);
    }
}

